### PR TITLE
Remove interface Applier

### PR DESCRIPTION
**Pull request by robertvolkmann**
- [No changes necessary for firewall-controller.](https://github.com/metal-stack/firewall-controller/blob/686a7e03b4f5bb85965c6c98d71f5953e467f08a/pkg/network/network.go#L54)
- [metal-core needs to adapt]{https://github.com/metal-stack/metal-core/blob/6b2d3687e2fb9cb8895c0a19ee2235f4e571cdef/internal/switcher/frr.go#L26}

### CODE REVIEW

**Comment by robertvolkmann** [comment]
@majst01 I struggle to find a better name for NetworkApplier. My hands resist renaming it to Applier.

**Comment by majst01** [comment]
> @majst01 I struggle to find a better name for NetworkApplier. My hands resist renaming it to Applier.

NetworkApplier is fine

**Comment by robertvolkmann** [comment]
Created https://github.com/metal-stack/metal-core/pull/70 to inline `metal-networker` in `metal-core`.

**Comment by majst01** [comment]
Is this still required ?

**Comment by robertvolkmann** [comment]
This refactoring can be merged because the blocker in metal-core is resolved.

**Pull request closed without merging**
